nacos:
  config:
    server-addr: 192.168.3.208:8848
    bootstrap:
      enable: true
      log-enable: true
    auto-refresh: true
    type: yaml
    group: YSM
    data-ids: ${spring.application.name}-${spring.profiles.active}.yml,${spring.application.name}.yml
    namespace: ysm
logging:
  level:
    com.ycicic.ysm: info
    org.springframework: warn