server:
  port: 11004
spring:
  application:
    name: ysm
  profiles:
    active: pord

nacos:
  config:
    server-addr: nacos:8848
    bootstrap:
      enable: true
      log-enable: true
    auto-refresh: true
    type: yaml
    group: YSM
    data-ids: ${spring.application.name}-${spring.profiles.active}.yml,${spring.application.name}.yml
logging:
  level:
    root: info
